"""What the displayed numbers mean, read off the record that produced them.

A step score is uncalibrated, so the honest caveat is not "this number is uncertain" but
*this checkpoint catches these failures and misses those*. That is a property of the
selection record, and it is retyped at the reader's peril: drafting this footer by hand
produced two different wrong paraphrases of the same file — one understating the overlap,
one crediting the champion with catching a family it splits on. So every figure here is
derived from `data/verifier/selection.json` at render time, and no band literal appears in
any surface module.

**Matching is on the checkpoint, revision and recipe — not the whole scorer id.**
`ScorerSpec.scorer_id` appends `+label-order-unverified` when label-order verification was
skipped, so matching the full string would fail exactly when a run's numbers are *least*
trustworthy, and drop the caveat at the moment it matters most. The base is matched and
the flag is surfaced on its own line.

**Populations are not pooled silently.** `min_max_margin` is reported over the four
deciding corrupt cases the selection rule scored, and is read verbatim rather than
recomputed over the pooled cases — recomputing it against a different population is the
drift this module exists to prevent. The family counts do pool the record's probe,
deciding-corrupt, diagnostic and blind-spot roles, and say so, because a reader who opens
the record and finds `n_corrupt: 4` has to be able to reconcile it with seven families.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

#: The committed record. Machine-generated by `python -m verity.verifier smoke`.
SELECTION = Path("data/verifier/selection.json")

#: Suffix `ScorerSpec.scorer_id` appends when label-order verification was skipped.
LABEL_ORDER_SUFFIX = "+label-order-unverified"

#: Record labels rendered as prose. A label absent here prints verbatim — an unrecognized
#: corruption family is reported, never dropped.
_FAMILY_NAMES = {
    "clean": "clean step",
    "probe": "swapped conclusion",
    "corrupt-premise-negated": "negated premise",
    "corrupt-conclusion-overreach": "conclusion overreach",
    "diagnostic-inconsistent-premise-set": "inconsistent premise set",
    "diagnostic-premise-dropped": "dropped premise",
    "diagnostic-irrelevant-injected": "irrelevant premise injected",
    "blind-spot": "blind spot",
}


@dataclass(frozen=True)
class Family:
    """One corruption family, and how much of it this checkpoint caught."""

    label: str
    caught: int
    total: int
    unscored: int = 0

    @property
    def name(self) -> str:
        return _FAMILY_NAMES.get(self.label, self.label)

    @property
    def tally(self) -> str:
        return f"{self.name} {self.caught}/{self.total}"


@dataclass(frozen=True)
class ScorerRecord:
    """The selection record's account of one checkpoint, at one gate."""

    scorer_id: str
    label_order_verified: bool
    gate: float
    caught: tuple[Family, ...]
    split: tuple[Family, ...]
    missed: tuple[Family, ...]
    clean: Family | None
    min_max_margin: float | None
    n_corrupt: int
    n_cases: int
    stable_gate_range: tuple[float, float] | None
    source: Path

    @property
    def family_count(self) -> int:
        return len(self.caught) + len(self.split) + len(self.missed)


def _compose_id(spec: dict) -> str:
    """`ScorerSpec.scorer_id` without the label-order suffix, rebuilt from the record.

    The record stores the spec's fields, not the composed id, so the composition lives in
    two places. It is pinned by a test against `ScorerSpec` itself rather than trusted.
    """
    return f"{spec['checkpoint']}@{spec['revision'][:7]}+{spec['recipe']}"


def base_id(scorer_id: str) -> tuple[str, bool]:
    """Split a stored `Score.scorer` into its base and whether label order was verified."""
    if scorer_id.endswith(LABEL_ORDER_SUFFIX):
        return scorer_id[: -len(LABEL_ORDER_SUFFIX)], False
    return scorer_id, True


def _families(cases: Iterable[dict], scorer_key: str, gate: float) -> list[Family]:
    grouped: dict[str, list[float | None]] = {}
    for case in cases:
        grouped.setdefault(case["label"], []).append(case.get(scorer_key))
    families = []
    for label, scores in grouped.items():
        scored = [s for s in scores if s is not None]
        families.append(
            Family(
                label=label,
                caught=sum(1 for s in scored if s < gate),
                total=len(scored),
                unscored=len(scores) - len(scored),
            )
        )
    return families


def _stable_gate_range(
    scores: Sequence[float], gate: float
) -> tuple[float, float] | None:
    """The interval of gates over which every case classifies as it does now.

    Reported because the configured gate is a placeholder (`VerifierConfig`), and a
    reader is entitled to know whether the counts above depend on it. `None` when no
    interval exists, which would mean a case sits exactly on the gate.
    """
    below = [s for s in scores if s < gate]
    above = [s for s in scores if s >= gate]
    if not below or not above:
        return None
    low, high = max(below), min(above)
    return (low, high) if low < high else None


def load(path: Path | str = SELECTION, *, gate: float) -> dict[str, ScorerRecord]:
    """Every checkpoint in the record, keyed by its base scorer id."""
    path = Path(path)
    payload = json.loads(path.read_text(encoding="utf-8"))
    cases = list(payload.get("per_case", {}).values())

    records: dict[str, ScorerRecord] = {}
    for key, spec in payload.get("scorers", {}).items():
        families = _families(cases, key, gate)
        clean = next((f for f in families if f.label == "clean"), None)
        corruption = [f for f in families if f.label != "clean"]
        summary = payload.get("summaries", {}).get(key, {})
        scores = [c[key] for c in cases if c.get(key) is not None]
        records[_compose_id(spec)] = ScorerRecord(
            scorer_id=_compose_id(spec),
            label_order_verified=bool(spec.get("label_order_verified", True)),
            gate=gate,
            caught=tuple(f for f in corruption if f.total and f.caught == f.total),
            split=tuple(f for f in corruption if 0 < f.caught < f.total),
            missed=tuple(f for f in corruption if f.total and f.caught == 0),
            clean=clean,
            # Read verbatim: the record computed it over the deciding corrupt cases, and
            # recomputing it over the pooled set would answer a different question.
            min_max_margin=summary.get("min_max_margin"),
            n_corrupt=int(summary.get("n_corrupt", 0)),
            n_cases=len(cases),
            stable_gate_range=_stable_gate_range(scores, gate),
            source=path,
        )
    return records


def for_scorers(
    scorer_ids: Sequence[str], *, gate: float, path: Path | str = SELECTION
) -> tuple[ScorerRecord | None, str | None]:
    """The record describing the scorer that produced a payload's numbers.

    Returns `(record, note)`. `note` is set whenever a caveat cannot be stated —
    no scorer on the rows, no record on disk, more than one checkpoint in one graph, or a
    checkpoint the record does not describe. Saying which of those happened is the point:
    a surface that silently omitted the caveat would look identical to one that had
    nothing to caveat.
    """
    ids = [s for s in dict.fromkeys(scorer_ids) if s]
    if not ids:
        return None, None
    if len(ids) > 1:
        return None, (
            f"{len(ids)} checkpoints produced the numbers in this graph "
            f"({', '.join(ids)}); no single selection record describes them"
        )

    scorer_id = ids[0]
    base, verified = base_id(scorer_id)
    path = Path(path)
    if not path.exists():
        return None, f"no selection record at {path}, so no scorer caveat can be stated"

    record = load(path, gate=gate).get(base)
    if record is None:
        return None, (
            f"{path} describes no checkpoint matching {base}; these numbers come from a "
            "scorer the committed selection record does not cover"
        )
    if not verified:
        record = ScorerRecord(**{**record.__dict__, "label_order_verified": False})
    return record, None


def summary_lines(record: ScorerRecord) -> list[str]:
    """The footer's scorer caveat. Every figure derived, none typed."""
    # No trailing punctuation: a scorer id is one long unbreakable token, and a period
    # after it folds onto a line of its own.
    lines = [f"Scores come from {record.scorer_id}"]

    def tallies(families: tuple[Family, ...]) -> str:
        return ", ".join(f.tally for f in families)

    clauses = []
    if record.caught:
        clauses.append(f"catches {len(record.caught)} outright ({tallies(record.caught)})")
    if record.split:
        clauses.append(f"splits on {len(record.split)} ({tallies(record.split)})")
    if record.missed:
        clauses.append(f"misses {len(record.missed)} entirely ({tallies(record.missed)})")
    if clauses:
        lines.append(
            f"Read at the {record.gate:g} gate, of the {record.family_count} corruption "
            f"families in the M4-T1 smoke set ({record.n_cases} cases, pooling the "
            f"record's probe, deciding-corrupt, diagnostic and blind-spot roles) it "
            + "; ".join(clauses)
            + "."
        )
    if record.clean is not None:
        flagged = record.clean.caught
        lines.append(
            f"It flags {flagged} of the {record.clean.total} clean steps."
            if flagged
            else f"It flags none of the {record.clean.total} clean steps."
        )
    if record.min_max_margin is not None:
        overlap = (
            "the clean and corrupt bands overlap"
            if record.min_max_margin < 0
            else "the bands do not overlap"
        )
        lines.append(
            f"The selection rule scored only the {record.n_corrupt} deciding corrupt "
            f"cases; over those the min−max margin is {record.min_max_margin:+g}, so "
            f"{overlap}."
        )
    if record.stable_gate_range is not None:
        low, high = record.stable_gate_range
        lines.append(
            f"Those counts are unchanged for any gate in ({low:g}, {high:g}]."
        )
    if not record.label_order_verified:
        lines.append(
            "Label-order verification was disabled for this run, so which output index "
            "means entailment was assumed rather than checked."
        )
    lines.append(
        "A high score means the step was not caught, not that the step is that likely to "
        f"hold. Full record: {record.source} and data/verifier/README.md."
    )
    return lines
